# Generated by Django 2.0.5 on 2018-06-18 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos_indirectos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subsidios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poblacion', models.IntegerField()),
                ('can_Ampliada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_Minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anios_simulados', models.IntegerField()),
                ('iva_simulado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSim', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('varEntrada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulacion.DatoEntrada')),
            ],
        ),
        migrations.CreateModel(
            name='VariableMacro',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreMacro', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
        ),
        migrations.AddField(
            model_name='simulacion',
            name='variablesM',
            field=models.ManyToManyField(blank=True, to='simulacion.VariableMacro'),
        ),
    ]
